---
id: micronomy
endpoints:
  - id: https
    host-env: MICRONOMY_HOST
    name: HTTPS
    port-env: MICRONOMY_PORT
    protocol: https
name: micronomy
entrypoint: service.p6
cro: 1
env:  []
links:  []
...
